### ISSUE TITLE
New command "split" to create input datasets for k-fold cross-validation

### ISSUE THREAD

**Issue by marcostorrework** [ersilia-os/zaira-chem#12]
**Is your feature request related to a problem? Please describe.**
Not related to any problem.

**Describe the solution you'd like**
Syntax example:
`zairachem split -i input_file.csv --folds_dir folds --num_folds 5`
This would create dataset splits for 5 folds, stored in 5 directories within directory "folds", as follows:
* folds
    - fold-0
        + train.csv
        + test.csv
    - fold-1
        + train.csv
        + test.csv
    - ...

Each of the five test.csv files contains 1/5 of the data, with no common cases between them.
The train.csv file in each fold contains the other 80% of the data not contained in test.csv

The idea is that, afterwards, the user may run the following commands for each fold:
`zairachem fit -i folds/fold-0/train.csv -m folds/fold-0/model`
`zairachem predict -i folds/fold-0/test.csv -m folds/fold-0/model -o folds/fold-0/test --flush`

num_folds must be at least 2. A reasonable maximum value might be 20.

if the folds_dir directory exists and is not empty, stop the execution.
If the folds_dir directory does not exist, the program will create it.

**Describe alternatives you've considered**
Current alternative is that the user creates the split datasets manually.

**Additional context**
https://en.wikipedia.org/wiki/Cross-validation_(statistics)#k-fold_cross-validation

**Comment by miquelduranfrigola** [comment]
Hi @marcostorrework just to keep track of things, I have assigned you to this issue. Your suggested solution looks great.

**Comment by marcostorrework** [comment]
For the current version, the number of folds is fixed at 5. The reason is that we rely on the "fold" variable generated by the TrainSetup method. This allows using different criteria for the fold assignment: "random" (fld_rnd), "scaffold" (fld_scf), "similarity" (fld_lsh), and "standard" (fld_aux).
