### ISSUE TITLE
Option for quick fit of a basic model

### ISSUE THREAD

**Issue by marcostorrework** [ersilia-os/zaira-chem#14]
**Is your feature request related to a problem? Please describe.**
Modelers often need to do trial-and-error with different versions of the input datasets before generating the final versions of the models. For this, it is very helpful to have a modeling tool that provides quick results, even if the model accuracy is not high.
We could add "quick" option to fit zairachem models that builds a basic working model quickly (a few minutes maximum).

**Describe the solution you'd like**
A new option "--quick" to be used in the fit command, something like:
zairachem fit [...] --quick
When using this option, zairachem would skip the heavier steps in the modeling pipeline.

**Describe alternatives you've considered**
Currently a (less convenient) posibility is to use the "lazyQSAR" tool from Ersilia for model prototyping, and then go back to Zairachem when we know exactly what we want.

**Additional context**
N/A

**Comment by miquelduranfrigola** [comment]
Working on it. Naming this option `--lazy` for consistency with our library [LazyQSAR](https://github.com/ersilia-os/lazy-qsar). Will keep you posted.

**Comment by miquelduranfrigola** [comment]
This is now done. Closing issue!
