### ISSUE TITLE
Isaura python version mismatch

### ISSUE THREAD

**Issue by JHlozek** [ersilia-os/zaira-chem#16]
**Describe the bug**
The recent changes to Isaura have Python>=3.8 as a requirement but zairachem is built in a 3.7 environment.

Isaura fails to install at this step: python3 -m pip install git+https://github.com/ersilia-os/isaura.git
with: ERROR: Package 'isaura' requires a different Python: 3.7.15 not in '<4.0,>=3.8'

The PYPI version of Isaura also has a Python>=3.8 requirement.
What worked for now was to rollback Isaura.

**To Reproduce**
1. setup zairachem with 'bash install_linux.sh'
2. run python3 -m pip install git+https://github.com/ersilia-os/isaura.git
3. See error

**Expected behavior**
Have Isaura install without a dependency crash

**Desktop (please complete the following information):**
 - OS: Ubuntu and CentOS

**Comment by miquelduranfrigola** [comment]
Thanks @JHlozek . I think we have solved the issue now. See the new install script.
