### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by nataliyah123** [ersilia-os/zaira-chem#18]
The read-me can be improved if you guys can add details like 
1. The required OS.
2. git clone url.
3. pip install git-lfs (mandatory or else you will have permission denied and checkout failure notification)
4. Remove sklearn and add scikit-learn from requirement.txt
5. Nvidia card is required or not.

**Comment by miquelduranfrigola** [comment]
Thanks @nataliyah123 . @GemmaTuron I have assigned it to you, but we can work on it together previous to / during submission of the paper.

**Comment by GemmaTuron** [comment]
the readme's are updated
