### ISSUE TITLE
eos3cf4 Descriptors failing in Docker

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/zaira-chem#36]
**Describe the bug**
Model eos3cf4 (MolFeat Chem GPT4.7M) gives Null outputs when fetched from DockerHub, not when fetched from GitHub. Docker Image is updated though to the same code as GitHub

**To Reproduce**
1. Try ersilia fetch eos3cf4 --from_dockerhub and compare with ersilia fetch eos3cf4 --from_github

**Expected behavior**
All molecules, even mock examples like "CCCC" should give a numeric output, not a list of Null

**Desktop (please complete the following information):**
 - OS: UBUNTU 22.04 LTS

**Comment by GemmaTuron** [comment]
IF the model is fetched, zairachem in principle works as it will not try to fetch again. IF it is not, It will attempt fetching from DockerHub, which "works" but gives the Null outputs

Ersilia code pulled today (22.03.24)

**Comment by GemmaTuron** [comment]
This is also happening with the model eos78ao
@DhanshreeA I am sorry I am unable to provide more information on understanding why this might be happening, could have something to do with the reformating we have made lately in ersilia or not, but two action items are becoming prioritary seeing that it is not a one model issue:

- [ ] Find the error and fix those models manually
- [ ] Create a workflow that checks if the docker containers run once built (run without giving null, they don't crash which is why we don't catch the error)

@miquelduranfrigola @DhanshreeA would you agree that this is kind of prioritary? at least finding out why?

**Comment by miquelduranfrigola** [comment]
I don't know what might be happening but clearly the best would be to find a way of checking if dockerized models work before pushing them to dockerhub.

It is 100% prioritary in my opinion.

**Comment by GemmaTuron** [comment]
Correction:
This seems to be related to the clean up we were doing to reduce Docker space and free space on the GitHub runner. Which means all models that are updated with the newest workflow to date will not work via Docker

**Comment by DhanshreeA** [comment]
Hey all, model eos3cf4 is up and working now.

**Comment by GemmaTuron** [comment]
Thanks @DhanshreeA !
Should I close this issue or leave it open until we are sure the issue with Docker containers has been solved generally?

**Comment by DhanshreeA** [comment]
I believe we can close this issue since the problem with this model was unique in that it had a missing dependency (https://github.com/ersilia-os/eos3cf4/issues/10) which had to be fixed within the model's codebase. I am tracking the general problem with Docker builds here in any case: https://github.com/ersilia-os/ersilia/issues/1098
