### ISSUE TITLE
ZairaChem fresh installation troubleshooting

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/zaira-chem#41]
Hi @sucksido

Please note here the troubleshooting you did to install ZairaChem from afresh so we can add pointers for future users

**Comment by JHlozek** [comment]
I encountered the following issue where FLAML broke after fetching an Ersilia model in the ZairaChem environment:
_RUNTIMEENVURIS = DESCRIPTOR.message_types_by_name['RuntimeEnvUris']
AttributeError: 'NoneType' object has no attribute 'message_types_by_name'

Setting up Docker and/or re-installing ZairaChem was a workaround for me. However, I couldn't install Docker Desktop on Rocky Linux and instead followed the instructions at the following two links:
https://docs.docker.com/desktop/install/rhel/
https://docs.docker.com/engine/install/linux-postinstall/

**Comment by JHlozek** [comment]
The mordred (eos78ao) model doesn't currently save its output correctly which leaves only a 'raw.h5' file in /model/descriptors/mordred as compared to the other descriptors that have multiple post-processing files.

Until this is debugged, the issue can be solved by editing the /home/user/eos/dest/eos78ao/api_schema.json file to the following:
[api_schema.json](https://github.com/ersilia-os/zaira-chem/files/15047975/api_schema.json)

**Comment by sucksido** [comment]
Getting the following errors:

Command: ersilia fetch eos3cf4 --from_dockerhub


Error: 🚨🚨🚨 Something went wrong with Ersilia 🚨🚨🚨

Error message:

Ersilia exception class:
DockerNotActiveError

Detailed error:
Cannot fetch model from Docker Hub since Docker is not active.

Hints:
Make sure that Docker is running on your computer. We recommend to use Docker Desktop.

****Even When Docker is running****

When I run the following command, it runs forever and eventually times out:

ersilia fetch eos3cf4

**Comment by GemmaTuron** [comment]
Hi @sucksido 

The error is on your side, as you can see, you do not have Docker active. Please make sure Docker is properly installed and working in your system

**Comment by JHlozek** [comment]
Hi @sucksido

If docker is working outside of the ZairaChem pipeline (i.e. you can run 'docker info' correctly), I needed to follow this guide to give it the correct permissions: https://docs.docker.com/engine/install/linux-postinstall/

**Comment by sucksido** [comment]
Thanks @JHlozek , let me follow the guide, I will let you know how it goes.

**Comment by sucksido** [comment]
Thanks @JHlozek , I have managed to get past the docker issue, I have also managed to build a model, however I get this error at the end

**Comment by sucksido** [comment]
`  File "/home/success/anaconda3/envs/zairachem/bin/zairachem", line 33, in <module>
    sys.exit(load_entry_point('zairachem', 'console_scripts', 'zairachem')())
  File "/home/success/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/success/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/success/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/success/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/success/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/success/code/zaira-chem/zairachem/cli/commands/fit.py", line 128, in fit
    e.run()
  File "/home/success/code/zaira-chem/zairachem/estimators/pipe.py", line 161, in run
    self._classic_estimator_pipeline(time_budget_sec)
  File "/home/success/code/zaira-chem/zairachem/estimators/pipe.py", line 62, in _classic_estimator_pipeline
    p.run(time_budget_sec=time_budget_sec)
  File "/home/success/code/zaira-chem/zairachem/estimators/from_classic/pipe.py", line 9, in run
    self.e.run(time_budget_sec=time_budget_sec)
  File "/home/success/code/zaira-chem/zairachem/estimators/from_classic/estimate.py", line 168, in run
    results = self.estimator.run()
  File "/home/success/code/zaira-chem/zairachem/estimators/from_classic/estimate.py", line 81, in run
    estimator.fit(data=df.iloc[train_idxs, :], labels=labels)
  File "/home/success/code/zaira-chem/zairachem/automl/classic.py", line 428, in fit
    self.clf_estimator.fit(X, np.array(data_clf).ravel())
  File "/home/success/code/zaira-chem/zairachem/automl/classic.py", line 325, in fit
    self.fit_automl(smiles, y)
  File "/home/success/code/zaira-chem/zairachem/automl/classic.py", line 304, in fit_automl
    X = self.descriptor.fit(smiles)
  File "/home/success/code/zaira-chem/zairachem/automl/classic.py", line 264, in fit
    df = classic_featurizer(smiles)
  File "/home/success/code/zaira-chem/zairachem/automl/classic.py", line 242, in classic_featurizer
    descriptors = _calculate_rdkit_descriptors(m)
  File "/home/success/code/zaira-chem/zairachem/automl/classic.py", line 218, in _calculate_rdkit_descriptors
    calc_apol(mol),
  File "/home/success/code/zaira-chem/zairachem/automl/classic.py", line 201, in calc_apol
    atom_pols = [float(x) for x in next(f).split(",")]
  File "/home/success/code/zaira-chem/zairachem/automl/classic.py", line 201, in <listcomp>
    atom_pols = [float(x) for x in next(f).split(",")]
ValueError: could not convert string to float: 'version https://git-lfs.github.com/spec/v1\n'
`

**Comment by GemmaTuron** [comment]
Hi @sucksido 

Please:
- Copy the error as log files (.txt) makes it much easier to read
- Explain what have you tried already to solve the error so we don't get overlap
- Ensure git lfs is properly installed 
- Ensure the latest zairachem code is being pulled

Please add all the detail you can instead of just pasting error messages without explanation, it makes it very difficult to understand what might be happening otherwise. I also noted that you were able to run zairachem as you mention in #43 ? so what did you change?

**Comment by sucksido** [comment]
> ` File "/home/success/anaconda3/envs/zairachem/bin/zairachem", line 33, in <module> sys.exit(load_entry_point('zairachem', 'console_scripts', 'zairachem')()) File "/home/success/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__ return self.main(*args, **kwargs) File "/home/success/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main rv = self.invoke(ctx) File "/home/success/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/home/success/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke return ctx.invoke(self.callback, **ctx.params) File "/home/success/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke return __callback(*args, **kwargs) File "/home/success/code/zaira-chem/zairachem/cli/commands/fit.py", line 128, in fit e.run() File "/home/success/code/zaira-chem/zairachem/estimators/pipe.py", line 161, in run self._classic_estimator_pipeline(time_budget_sec) File "/home/success/code/zaira-chem/zairachem/estimators/pipe.py", line 62, in _classic_estimator_pipeline p.run(time_budget_sec=time_budget_sec) File "/home/success/code/zaira-chem/zairachem/estimators/from_classic/pipe.py", line 9, in run self.e.run(time_budget_sec=time_budget_sec) File "/home/success/code/zaira-chem/zairachem/estimators/from_classic/estimate.py", line 168, in run results = self.estimator.run() File "/home/success/code/zaira-chem/zairachem/estimators/from_classic/estimate.py", line 81, in run estimator.fit(data=df.iloc[train_idxs, :], labels=labels) File "/home/success/code/zaira-chem/zairachem/automl/classic.py", line 428, in fit self.clf_estimator.fit(X, np.array(data_clf).ravel()) File "/home/success/code/zaira-chem/zairachem/automl/classic.py", line 325, in fit self.fit_automl(smiles, y) File "/home/success/code/zaira-chem/zairachem/automl/classic.py", line 304, in fit_automl X = self.descriptor.fit(smiles) File "/home/success/code/zaira-chem/zairachem/automl/classic.py", line 264, in fit df = classic_featurizer(smiles) File "/home/success/code/zaira-chem/zairachem/automl/classic.py", line 242, in classic_featurizer descriptors = _calculate_rdkit_descriptors(m) File "/home/success/code/zaira-chem/zairachem/automl/classic.py", line 218, in _calculate_rdkit_descriptors calc_apol(mol), File "/home/success/code/zaira-chem/zairachem/automl/classic.py", line 201, in calc_apol atom_pols = [float(x) for x in next(f).split(",")] File "/home/success/code/zaira-chem/zairachem/automl/classic.py", line 201, in <listcomp> atom_pols = [float(x) for x in next(f).split(",")] ValueError: could not convert string to float: 'version https://git-lfs.github.com/spec/v1\n'`

The solution to this error was to run `git lfs pull`
