### ISSUE TITLE
Run ZairaChem end to end

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/zaira-chem#43]
@JHlozek has identified interesting datasets to work with.  @sucksido will attempt to build a model with them to make sure ZairaChem is working for him
@jhlozek, is the data open? Can you point to the files?

Thanks!

**Comment by JHlozek** [comment]
@GemmaTuron, these are the data files I sent to Success to work with. The data is a small subset from ChEMBL and CO-ADD for _A baumannii_ activity at 32 ug/ml.

[amr_small_test.csv](https://github.com/ersilia-os/zaira-chem/files/15096873/amr_small_test.csv)
[amr_small_train.csv](https://github.com/ersilia-os/zaira-chem/files/15096874/amr_small_train.csv)

**Comment by sucksido** [comment]
I am able to run the 2 test files and getting some results. @JHlozek let me know when you are free so we can touch base

**Comment by GemmaTuron** [comment]
Hi @sucksido what did you change that you are now encountering errors?

**Comment by sucksido** [comment]
@GemmaTuron i was getting an error when I run the `fit` command but it is resolved now, all I had to do it run `git lfs pull`

**Comment by sucksido** [comment]
Hi guys,

Update: 

I have managed to run ZairaChem end to end, managed to build the `fit` and the `predict` model

How I got through the errors i encountered.

Docker error: I follwed this guide: https://docs.docker.com/engine/install/linux-postinstall/

Git lfs error: ran `git lfs pull`

Tomorrow I will working on Incorporating a model in Ersilia

**Comment by GemmaTuron** [comment]
Hi @sucksido 

As we discussed in the last meeting, please tomorrow show the results of these runs, a five fold crossval or at least a result with a single train test split.
Also an overview of the dataset would be useful to understand the data.

**Comment by sucksido** [comment]
ZairaChem Test Results (Reports): 
![image](https://github.com/ersilia-os/zaira-chem/assets/8820397/4844b444-7586-4f22-91e3-532849f358e7)
![image](https://github.com/ersilia-os/zaira-chem/assets/8820397/d0f8e03a-e7d7-4463-bdd5-f8f88ac2074f)
![image](https://github.com/ersilia-os/zaira-chem/assets/8820397/5235b071-337f-4c7b-820d-870a7fdd8563)
![image](https://github.com/ersilia-os/zaira-chem/assets/8820397/1f593b8f-19ad-491b-adc7-e8e4410a0af5)
![image](https://github.com/ersilia-os/zaira-chem/assets/8820397/0f541958-397d-4a43-b54f-3a889cb00a0c)
![image](https://github.com/ersilia-os/zaira-chem/assets/8820397/41ec11a9-8898-44cf-b4cf-f62cf61c2a07)
![image](https://github.com/ersilia-os/zaira-chem/assets/8820397/105e86a1-4130-4e60-b93b-87d003e37f7f)
![image](https://github.com/ersilia-os/zaira-chem/assets/8820397/c05a04cc-2291-455a-bbc3-882ec657121e)
