### ISSUE TITLE
Add CLI command for distillation

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/zaira-chem#47]
If we have created ZairaChem in a way that it installs olinda, it should then have a command named "distill" that basically calls on the Olinda distill command (see ersilia-os/olinda#11)

**Comment by JHlozek** [comment]
I actually implemented this already before the Olinda improvements were suggested and followed a similar formatting to the other ZairaChem commands. 
Let me know if you prefer it to rather call the Olinda cli more directly though a Click Context (though Click says this is discouraged: https://click.palletsprojects.com/en/stable/advanced/#invoking-other-commands).

Currently, ZairaChem now has a ```distill``` command that takes a ```-m``` argument for the ZairaChem model path (eventually also more generally for Ersilia or other models) and a ```-o``` argument for the output filepath of the resulting .onnx model.

**Comment by GemmaTuron** [comment]
oh great I think that works fine as you suggest @JHlozek !
