### ISSUE TITLE
Hard coded paths

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/zaira-chem#5]
**Describe the bug**
The fp2sim_X_notnan.h5 file path is stored as the original directory where it was trained, hence models cannot run in another directory/user/workstation

**To Reproduce**
1. Train a model in one directory or workstation
2. Copy model to another directory
3. Try to predict with the model

**Expected behavior**
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '/home/<userpath>/<modelname>/descriptors/fp2sim_X_notnan.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by miquelduranfrigola** [comment]
Solved in commit 6d5c8598319cc0a80989caf3d1e1c0d0485072b7
