### ISSUE TITLE
`install_linux.sh` script is not working for m1 mac.

### ISSUE THREAD

**Issue by leoank** [ersilia-os/zaira-chem#6]
**Describe the bug**
`install_linux.sh` script is not working for m1 mac.
I realize that this script is meant to work only for Linux systems.
But, even on Linux systems, the script can have unintended behavior.
For example, the installation is split into multiple steps and the script doesn't abort if one of the steps fails.
This can lead to broken installations and hard to debug issues later.

**To Reproduce**
1. execute `bash install_linux.sh` on an m1 mac

**Expected behavior**
executing `bash install_linux.sh` should have installed `zairachem` on the system

**Desktop (please complete the following information):**
 - OS: macOS 12.3

**Comment by miquelduranfrigola** [comment]
Hi @leoank thanks for raising this issue. I agree with your points. Please feel free to work in a Python script to replace the current bash script, as well as adding checks.

**Comment by miquelduranfrigola** [comment]
Hi @leoank  did you make any progress on this end?

**Comment by leoank** [comment]
Hey @miquelduranfrigola, I have some notes and I did some work on adapting a python script that I wrote for a different project. But, it wasn't on priority. So, I not working on it actively. If this is urgent then I can spend some time on closing this issue.

**Comment by miquelduranfrigola** [comment]
Update: I have figured out a way of making ersilia work on mac m1, although I haven't tested in on zairachem. Closing the issue for now.
