### ISSUE TITLE
Incompatible SMILES with Mellody

### ISSUE THREAD

**Issue by JHlozek** [ersilia-os/zaira-chem#7]
**Describe the bug**
Zaira initialisation fails due to a specific SMILES string that MellodyTuner doesn't process, which then causes a crash during calculation of the different folds. Offending SMILES: "CCCCCCCCC[c-]1c(=N)on[n+]1C"

**To Reproduce**
1. zaira fit -c 50 -d high -i on CO-ADD_InhibitionData_r03_01-02-2020_CSV_-10000_-5000_train.csv -o <output_path>

**Expected behavior**
If Mellody could not assign a fold, then catch the exception (log file attached) and randomly assign a fold.

**Desktop (please complete the following information):**
 - OS: CentOS Stream release 8

[CO-ADD_InhibitionData_r03_01-02-2020_CSV_-10000_-5000_train.csv](https://github.com/ersilia-os/zaira-chem/files/8467479/CO-ADD_InhibitionData_r03_01-02-2020_CSV_-10000_-5000_train.csv)
[CO-ADD_InhibitionData_r03_01-02-2020_CSV_-10000_-5000_train_log.txt](https://github.com/ersilia-os/zaira-chem/files/8467482/CO-ADD_InhibitionData_r03_01-02-2020_CSV_-10000_-5000_train_log.txt)

**Additional context**

**Comment by miquelduranfrigola** [comment]
Hi @JHlozek this has now been solved - a fold is randomly assigned when none is found. Will commit promptly.
